version: '3.5'
networks:
  frontend:
    driver: bridge
services:
  mongodb:
  image: mongodb:v1
  container_name: mongodb
  catalouge:
    image: catalouge:v1
    container_name: catalouge
    depends_on:
      - mongodb
    Web:
      image: web:v1
      container_name: Web
      depends_on:
      - catalouge
    redis:
      image: redis  
    user: 
      image: user:v1
      container_name: user
      depends_on:
      - mongodb
      - redis

