apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    name: newnginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service123
spec:
  selector:
    name: newnginx
  ports:
  - name: clusterIp
    protocol: TCP
    port: 80
    targetPort: 80
