---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    server: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service123
spec:
  selector:
    server: nginx
  ports:
  - name: clusterIp
    protocol: TCP
    port: 80
    targetPort: 80
